import fs from 'node:fs';
fs.mkdirSync('data/probe', { recursive: true });
const UA = 'rankingzip/1.0 (https://mktperiod-a11y.github.io/rankingzip/)';
const ids = [178789, 189046, 202269, 188139, 135865, 196187, 182205, 195600, 200637, 198946];
const q = `query ($ids: [Int]) { Page(perPage: 20) { media(id_in: $ids) { id title { english romaji native } coverImage { extraLarge } } } }`;
const r = await (await fetch('https://graphql.anilist.co', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ query: q, variables: { ids } }) })).json();
const log = r.data.Page.media.map((m) => `${m.id} | ${m.title.english} | ${m.title.romaji} | ${m.coverImage.extraLarge}`);
const slime = await (await fetch('https://graphql.anilist.co', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ query: `{ Page(perPage: 8) { media(search: "Tensei shitara Slime Datta Ken", type: ANIME) { id format seasonYear title { english romaji } coverImage { extraLarge } } } }` }) })).json();
for (const m of slime.data.Page.media) log.push(`slime? ${m.id} ${m.format} ${m.seasonYear} | ${m.title.english} | ${m.title.romaji} | ${m.coverImage.extraLarge}`);
const f = await fetch('https://commons.wikimedia.org/wiki/Special:FilePath/Flag_of_Chinese_Taipei_for_Olympic_games.svg?width=640', { headers: { 'user-agent': UA } });
log.push(`flag ${f.status} ${f.headers.get('content-type')} ${f.url}`);
if (f.ok) fs.writeFileSync('data/probe/chinese-taipei.png', Buffer.from(await f.arrayBuffer()));
fs.writeFileSync('data/probe/log.txt', log.join('\n') + '\n');
