import type { RankingPage, RankingRow } from './data';
import { netflixTv } from './netflix';
import webhard from '../../data/rankings/webhard.json';
import sources from '../../public/ranking-images/updates/sources.json';

const assets=sources as Record<string,{image:string;source?:string}>;
const art=(key:string)=>({image:assets[key]?.image,imageSource:assets[key]?.source});
const flag=(code:string)=>`https://flagcdn.com/w640/${code}.png`;
const num=(n:number)=>n.toLocaleString('en-US');
const holdReason:Record<string,string>={
 'mlb-korean-career-earnings':'기존 표에 계약 총액과 누적 수령액의 혼동 가능성이 있어 수치 및 순위 공개를 보류했습니다.',
 'korean-football-salary':'기본급·보장 보수·보너스와 환율 기준이 달라 기존 원화 순위를 보류했습니다. 확인한 개별 자료만 표시합니다.',
 'korean-travel-destinations':'국가별 집계기간·입국자 정의가 통일되지 않아 기존 방문자 수와 순위를 보류했습니다.',
 'japan-av-actress-ranking':'차트 날짜·측정치·가중치를 재현할 근거가 없어 기존 인기 순위 공개를 보류했습니다.',
};
export function applyAudit(pages:RankingPage[]):RankingPage[]{
 const get=(slug:string)=>{const p=pages.find(x=>x.slug===slug);if(!p)throw Error(slug);return p;};
 const assign=(slug:string,data:Partial<RankingPage>)=>Object.assign(get(slug),data);
 get('kbo-attendance-2026').rows.forEach((r,i)=>Object.assign(r,art(['LG_Twins','Samsung_Lions','Doosan_Bears','Lotte_Giants'][i])));
 for(const p of pages){p.auditDate='2026.09.17';p.holdReason=holdReason[p.slug];}
 assign('mlb-korean-career-earnings',{noindex:true,unranked:true,rows:[],title:'MLB 한국 선수 누적 연봉 · 검증 보류',date:'자료 재검증 중',basis:'누적 지급액·계약 총액 구분 필요',description:'기존 누적 연봉 표는 계약 보장 총액, 실제 지급액, 옵션을 같은 기준으로 확인할 수 없어 내렸습니다. 동일 기준의 시즌별 자료를 확보한 뒤 다시 공개합니다.',faq:[['왜 기존 순위가 보이지 않나요?','서로 다른 연봉 기준이 혼재할 수 있어 정확성이 확인될 때까지 숫자와 순위를 공개하지 않습니다.'],['계약 총액은 모두 받은 돈인가요?','아닙니다. 미래 지급액·옵션·보너스가 포함될 수 있습니다.']]});
 assign('japan-av-actress-ranking',{noindex:true,unranked:true,rows:[],title:'일본 성인 배우 인기 자료 · 검증 보류',date:'자료 재검증 중',basis:'원본 차트와 측정 기준 확보 필요',description:'기존 관심도 순위의 측정치와 집계 방식을 재현할 수 없어 순위 공개를 보류했습니다. 확인되지 않은 인기·상승 표현은 제공하지 않습니다.',faq:[['왜 순위 공개를 보류했나요?','원본 차트 날짜와 일관된 집계 기준을 확인하지 못했기 때문입니다.'],['기존 순위는 공식 순위였나요?','아닙니다. 공식 통합 인기 순위로 해석해서는 안 됩니다.']]});
 assign('korean-football-salary',{unranked:true,noindex:true,title:'한국 축구선수 연봉 자료 · 순위 검증 중',date:'2026.05.13 발표 자료',basis:'개별 보장 보수 자료 · 선수 간 순위 아님',description:'기존 한국 선수 원화 연봉 순위는 동일한 계약·환율 기준이 확보될 때까지 보류합니다. 아래는 확인한 개별 보수 자료이며 모든 한국 선수의 순위가 아닙니다.',source:'MLSPA 발표를 인용한 스포츠동아 보도',sourceUrl:'https://v.daum.net/v/20260513152101092',rows:[{name:'손흥민',value:'$11,152,852',note:'LAFC · 2026 보장 보수 · 기본급만의 수치 아님',image:'/ranking-images/son.jpg',sourceUrl:'https://v.daum.net/v/20260513152101092'}],faq:[['연봉 순위를 왜 보류했나요?','세전 기본급과 보장 보수, 보너스 포함 여부가 다른 자료를 원화로 섞어 비교했기 때문입니다.'],['이강인 소속팀 정보는 확인됐나요?','쿠팡의 2026년 8월 9일 공식 보도자료에서 아틀레티코 마드리드 입단을 확인했습니다. 소속팀 확인은 연봉 액수의 검증을 의미하지 않습니다.']]});
 assign('korean-travel-destinations',{unranked:true,noindex:true,title:'한국인 해외여행 통계 · 검증 중',date:'자료 재검증 중',basis:'동일 연도·방문자 정의 대조 필요',description:'기존 국가별 방문자 수는 여행 목적·입국자 집계 기준이 통일되지 않아 순위와 수치를 보류했습니다. 아래 국가들은 통계 확인 대상이며 인기 순서가 아닙니다.',rows:get('korean-travel-destinations').rows.map(r=>({...r,value:'비교 보류',note:'국가별 관광 통계 확인 대상'})),faq:[['왜 방문자 수를 내렸나요?','각국 입국자 수를 같은 정의와 기간으로 검증하지 못했기 때문입니다.'],['표시 순서가 인기 순위인가요?','아닙니다. 통계 확인 대상 국가의 목록입니다.']]});
 const kst=(iso:string)=>iso.replaceAll('-','.');
 assign('file-sharing-services',{unranked:false,auditDate:kst(webhard.updatedAt),title:'인기 웹하드 순위',date:`${kst(webhard.updatedAt)} 갱신`,basis:'순위ZIP 선정 · 2일마다 갱신',description:'국내 인기 웹하드 8곳 순위입니다.',source:'순위ZIP 선정',sourceUrl:'',rows:[...webhard.items].sort((x,y)=>x.rank-y.rank).map(it=>({name:it.name,value:'',note:'',rank:it.rank,sourceUrl:it.url,change:it.prevRank==null?'new' as const:it.prevRank-it.rank})),hideBars:true,rowLinkLabel:'사이트로 이동',faq:[]});
 assign('worldwide-box-office-2026',{date:'2026.08.31 확인',source:'Box Office Mojo · 2026 Worldwide',rows:[['스파이더맨: 브랜드 뉴 데이',2332507928,'Spider-Man:_Brand_New_Day'],['오디세이',1552604605,'The_Odyssey_(2026_film)'],['토이 스토리 5',1129456859,'Toy_Story_5'],['마이클',1021945850,'Michael_(2026_film)'],['슈퍼 마리오 갤럭시 무비',1013053769,'The_Super_Mario_Galaxy_Movie']].map(([name,v,key])=>({name:String(name),value:`$${num(Number(v))}`,note:'2026년 개봉작 · 전 세계 극장 누적 매출 · 8월 31일 확인',...art(String(key))})),faq:[['흥행 1위는 어떤 작품인가요?','2026년 8월 31일 확인한 표에서 스파이더맨: 브랜드 뉴 데이가 1위입니다.'],['극장 매출은 순이익인가요?','아닙니다. 제작·배급·마케팅 비용을 차감하지 않은 매출입니다.']]});
 const film=get('korea-box-office-2026');
 film.rows[3].name='군체';film.rows[4].name='호프';Object.assign(film.rows[1],art('Spider-Man:_Brand_New_Day'));Object.assign(film.rows[2],art('The_Odyssey_(2026_film)'));Object.assign(film.rows[4],art('Hope_(2026_film)'));
 film.rows.forEach((r,i)=>{r.sourceUrl=i===0||i===3?'https://v.daum.net/v/qJYKg7ztEa':'https://www.moviechart.co.kr/rank/boxoffice';r.note=i===0||i===3?'2026.08.02 보도 · 반올림 누적치':'2026.08.26까지 누적 관객';});
 film.title='2026년 개봉작 국내 누적 관객 순위';film.description='2026년 개봉작 중 확인한 흥행 상위 5편을 국내 누적 관객 수로 비교합니다. 상영연도 내 매출 순위와 다르며, 왕과 사는 남자·군체는 8월 2일 보도 반올림값입니다.';film.basis='2026년 개봉작 · 작품별 전체 누적 관객 · 집계 시점 혼합';film.source='영진위 자료를 인용한 무비차트·흥행 보도';film.sourceUrl='https://www.moviechart.co.kr/rank/boxoffice';
 film.faq=[['모든 수치가 같은 날짜의 집계인가요?','아닙니다. 각 행에 기준일을 표시했습니다. 왕과 사는 남자·군체는 과거 보도 반올림값이며, 상영 중인 세 작품은 8월 26일까지 누적값입니다.'],['영화 제목은 어떻게 수정했나요?','벌집과 희망으로 잘못 표시했던 작품을 국내 공식 제목인 군체와 호프로 정정했습니다.']];
 const alltime=get('korean-movie-admissions');alltime.rows=[alltime.rows[0],{...alltime.rows[2],value:'약 1,691만명',note:'2026 · 2026.08.02 보도',sourceUrl:'https://v.daum.net/v/qJYKg7ztEa'},alltime.rows[1],alltime.rows[3],alltime.rows[4]];alltime.date='2026.08.27 자료 확인';alltime.basis='국내 누적 관객 · 반올림 보도 기록';alltime.description='역대 국내 흥행 상위 작품을 누적 관객 수로 비교합니다. 왕과 사는 남자는 약 1,691만 관객으로 극한직업보다 위에 배치했습니다. 아래 수치는 반올림한 역사적 기록으로 실시간 정밀 집계가 아닙니다.';alltime.sourceUrl='https://www.kobis.or.kr/kobis/business/stat/boxs/findFormerBoxOfficeList.do';
 assign('ott-content-weekly',{title:'이번 주 넷플릭스 한국 TV TOP 10',...netflixTv});
 const ufc=get('ufc-rankings-by-division');ufc.date='2026.08.27 확인 · 공식 미디어 패널 차트';ufc.divisions![7].contenders[2]='세르게이 파블로비치';ufc.unranked=true;ufc.rows=ufc.rows.map(r=>({...r,note:r.name==='알렉산더 볼카노프스키'?'남성 P4P 2위':r.note}));ufc.description='남성부 8개 체급의 챔피언과 1~3위 랭커를 구분합니다. UFC 공식 페이지의 미디어 패널 차트를 사용하며, 데이터 기반 Meta 차트와는 별개입니다. 아래 주요 선수 소개에는 별도 순위를 부여하지 않습니다.';
 ufc.faq.push(['Meta 랭킹도 같은 순위인가요?','아닙니다. 공식 페이지의 별도 데이터 기반 차트입니다. 이 페이지는 미디어 패널 순위를 사용합니다.']);
 assign('korea-car-sales',{source:'다나와자동차 · 국산 모델 판매실적',date:'2026년 8월 · 9월 7일 확인',description:'2026년 8월 국내에서 많이 판매된 국산 모델 TOP 5입니다. 수입차와 중고차는 포함하지 않습니다.',rows:[['쏘렌토','6,397대','기아','sorento.png'],['더 뉴 그랜저','5,931대','현대','grandeur.jpg'],['카니발','4,186대','기아','carnival.png'],['스포티지','3,874대','기아','sportage.png'],['포터2','3,743대','현대','porter2.png']].map(([name,value,note,file])=>({name:String(name),value:String(value),note:String(note),image:`/ranking-images/cars/${file}`,sourceUrl:'https://auto.danawa.com/auto/?Work=record'})),faq:[['8월 국산차 판매 1위는 무엇인가요?','기아 쏘렌토가 6,397대로 1위입니다.'],['판매량과 등록 대수는 같나요?','자료원과 집계 시점에 따라 일부 차이가 날 수 있습니다.'],['수입차도 포함되나요?','이 표는 국산 모델 순위이며 수입차는 별도 집계입니다.']]});
 assign('korea-ott-users',{title:'국내 OTT 앱 사용자 순위 · 2025년 4월',source:'와이즈앱 조사 · 2025.05.27 보도',sourceUrl:'https://kbench.com/?q=node%2F267818',description:'2025년 4월 한국인 스마트폰 앱 사용자를 표본 조사한 과거 기록입니다. 현재 사용자나 유료 가입자 순위가 아닙니다.'});
 assign('korean-drama-ratings',{basis:'시대별 조사기관의 단일회 최고 시청률 기록 · 조사범위 상이',date:'역사적 기록 · 2026.08.27 확인',source:'시청률 기록 인용 보도',sourceUrl:'https://www.yna.co.kr/view/AKR20100627052600005',description:'역사적으로 보도된 지상파 드라마 최고 시청률을 정리했습니다. 과거 서울·수도권 중심 조사와 이후 전국 조사는 모집단이 달라 같은 전국 시청률로 해석할 수 없습니다. 케이블·OTT는 제외합니다.'});
 assign('highest-paid-athletes',{date:'Forbes 2026.05.22 발표 · 05.27 수정',basis:'발표 직전 12개월 경기·후원·사업 수입 · 세전 추정치',source:'Forbes · The World’s 10 Highest-Paid Athletes 2026',sourceUrl:'https://www.forbes.com/sites/brettknight/2026/05/22/the-worlds-10-highest-paid-athletes-2026/',rows:[{name:'크리스티아누 호날두',value:'$300,000,000',note:'축구'},{name:'카넬로 알바레스',value:'$170,000,000',note:'복싱'},{name:'리오넬 메시',value:'$140,000,000',note:'축구'},{name:'르브론 제임스',value:'$137,800,000',note:'농구'},{name:'오타니 쇼헤이',value:'$127,600,000',note:'야구'} ]});
 const buildingKeys=['Burj_Khalifa','Merdeka_118','Shanghai_Tower','Abraj_Al_Bait','Ping_An_Finance_Centre','Lotte_World_Tower'];get('world-tallest-buildings').rows.forEach((r,i)=>Object.assign(r,art(buildingKeys[i])));get('world-tallest-buildings').rows[1].note='쿠알라룸푸르 · 2023 · 현 표기 Menara Merdeka Maybank';get('world-tallest-buildings').date='2026.08.27 확인';
 assign('world-population',{date:'2025년 중간연도 · 2026.08.27 확인',basis:'UNFPA 공개 인구 추계 · WPP 2024 판본',source:'UNFPA World Population Dashboard',sourceUrl:'https://www.unfpa.org/data/world-population-dashboard',description:'UNFPA가 공개한 2025년 중간연도 인구 추계 TOP 5입니다. 2026년 실시간 인구가 아니며 원자료는 UN WPP 2024 판본입니다.',rows:[['인도',1463900000,'in'],['중국',1416100000,'cn'],['미국',347300000,'us'],['인도네시아',285700000,'id'],['파키스탄',255200000,'pk']].map(([name,v,code])=>({name:String(name),value:`${num(Number(v))}명`,note:'2025년 추계 · 공표 정밀도',image:flag(String(code)),sourceUrl:`https://www.unfpa.org/data/world-population/${String(code).toUpperCase()}`}))});
 assign('korea-province-population',{date:'2026년 7월 말',description:'행정안전부 주민등록 총인구 기준 상위 5개 시도입니다. 거주자·거주불명자·재외국민을 포함하고 외국인은 제외합니다. 해당 월 공식 행정구역 명칭을 사용합니다.',rows:[['경기도',13768157,'Gyeonggi_Province'],['서울특별시',9284263,'Seoul'],['부산광역시',3230982,'Busan'],['경상남도',3193742,'South_Gyeongsang_Province'],['전남광주통합특별시',3157777,'Gwangju']].map(([name,n,key])=>({name:String(name),value:`${num(Number(n))}명`,note:'2026년 7월 말 주민등록인구',...art(String(key))}))});
 const koreaKeys=['Hallasan','Jirisan','Seoraksan','Deogyusan','Gyebangsan'];const kp=get('korea-highest-mountains');kp.basis='남한 지역 · 산별 대표 정상 해발고도 · 부봉 제외';kp.source='산림청·한국민족문화대백과·국립공원공단·평창군';kp.sourceUrl='https://encykorea.aks.ac.kr/Article/E0061563';kp.rows.forEach((r,i)=>{Object.assign(r,art(koreaKeys[i]));r.sourceUrl=i===0?kp.sourceUrl:i===4?'https://tour.pc.go.kr/Home/H20000/H20200/placeDetail?place_no=10':`https://en.wikipedia.org/wiki/${koreaKeys[i]}`;});
 assign('world-gdp-ranking',{date:'IMF WEO 2026년 전망 · 2026.08.27 조회',basis:'명목 GDP · 현재 미 달러 · 전망치 · 국가만 비교',source:'IMF DataMapper · 명목 GDP (WEO)',sourceUrl:'https://www.imf.org/external/datamapper/NGDPD@WEO/OEMDC/ADVEC/WEOWORLD',rows:[['미국',32383.920,'us'],['중국',20851.593,'cn'],['독일',5452.858,'de'],['일본',4379.253,'jp'],['영국',4264.794,'gb'],['인도',4153.191,'in']].map(([name,v,code])=>({name:String(name),value:`${Number(v).toLocaleString('en-US',{minimumFractionDigits:3})}십억 달러`,note:'2026년 전망 · 1십억 달러 = 10억 달러',image:flag(String(code))}))});
 assign('world-largest-countries',{date:'2023년 자료 · 2026.08.27 대조',rows:[['러시아',16376870,'ru'],['중국',9388210,'cn'],['미국',9147420,'us'],['캐나다',8788700,'ca'],['브라질',8358140,'br']].map(([name,n,code])=>({name:String(name),value:`${num(Number(n))}㎢`,note:'내수면 제외 육지 면적 · 2023년',image:flag(String(code)),sourceUrl:`https://api.worldbank.org/v2/country/${String(code).toUpperCase()}/indicator/AG.LND.TOTL.K2?date=2023&format=json`}))});
 const worldKeys=['Mount_Everest','K2','Kangchenjunga','Lhotse','Makalu'];const wp=get('world-highest-mountains');wp.source='산별 백과사전 고도 자료';wp.sourceUrl='https://en.wikipedia.org/wiki/List_of_highest_mountains_on_Earth';wp.rows.forEach((r,i)=>{Object.assign(r,art(worldKeys[i]));r.sourceUrl=`https://en.wikipedia.org/wiki/${worldKeys[i]}`;});
 const tour=get('most-visited-countries');tour.date='2024년 통계 · 과거 기록';tour.source='UN Tourism 자료를 인용한 World Tourism rankings';tour.sourceUrl='https://en.wikipedia.org/wiki/World_Tourism_rankings';tour.rows[0].value='1억 200만명';tour.rows[4].value='약 5,790만명';tour.rows.forEach((r,i)=>{r.image=flag(['fr','es','us','tr','it'][i]);r.note='2024년 국제관광객 도착 수';});tour.description='2024년 국제관광객 도착 수 상위 국가를 비교한 과거 통계입니다. 현재 연도 순위가 아니며, 한 사람이 여러 번 방문한 경우 중복 집계될 수 있습니다.';
 const formerUrl='https://www.kobis.or.kr/kobis/business/stat/boxs/findFormerBoxOfficeList.do?loadEnd=0&searchType=search';
 const yearlyUrl='https://www.kobis.or.kr/kobis/business/stat/boxs/findYearlyBoxOfficeList.do?sSearchYearFrom=2026&loadEnd=0&searchType=search';
 alltime.rows.forEach((r,i)=>{r.value=`${num([17616791,16922332,16266641,14414658,14269712][i])}명`;r.note='KOBIS 역대 집계 · 2026.09.07 조회';r.sourceUrl=formerUrl;});
 Object.assign(alltime,{date:'2026.09.06까지 · 09.07 조회',basis:'KOBIS 역대 박스오피스 · 누적 관객',description:'영화진흥위원회 KOBIS 역대 박스오피스 상위 5편입니다. 왕과 사는 남자는 16,922,332명으로 2위입니다. 재개봉과 통계 보정에 따라 누적값은 변경될 수 있습니다.',source:'영화진흥위원회 KOBIS · 역대 박스오피스',sourceUrl:formerUrl});
 film.rows=[film.rows[0],film.rows[2],film.rows[1],film.rows[3],film.rows[4]];film.rows.forEach((r,i)=>{r.value=`${num([16922332,10027997,8792035,5845788,4540980][i])}명`;r.note='2026.09.06까지 · 09.07 KOBIS 조회';r.sourceUrl=yearlyUrl;});Object.assign(film.rows[3],art('Colony_(2026_film)'));
 Object.assign(film,{title:'2026년 국내 영화 흥행 순위',date:'2026.09.06까지 · 09.07 조회',basis:'KOBIS 2026년 상영기간 관객 · 상위 5편',description:'영화진흥위원회 KOBIS의 2026년 연도별 박스오피스 상위 5편입니다. 오디세이는 1,002만 관객을 넘어 2위를 유지했습니다. 상영기간 내 관객 기준이며 전년도 이월작도 포함됩니다.',source:'영화진흥위원회 KOBIS · 2026 연도별 박스오피스',sourceUrl:yearlyUrl,faq:[['집계 기준은 무엇인가요?','2026년 1월 1일부터 9월 6일까지 상영된 작품의 관객 수입니다. 이전 연도에 개봉한 이월작도 집계 대상입니다.'],['오디세이와 스파이더맨 관객 수는?','9월 6일까지 오디세이 10,027,997명, 스파이더맨 8,792,035명입니다.'],['관객 수는 바뀔 수 있나요?','KOBIS는 전일 집계를 익일 오전까지 보정할 수 있어 이후 소폭 변동될 수 있습니다.']]});
 const nolan=get('christopher-nolan-korea-box-office');[10387691,10027997,6428574,6014915,4283639].forEach((v,i)=>{nolan.rows[i].value=`${num(v)}명`;nolan.rows[i].note=i===1?'KOBIS 누적 집계 · 2026.09.06까지':'KOBIS 누적 집계 · 2026.09.07 조회';nolan.rows[i].sourceUrl=i===1?yearlyUrl:formerUrl;});nolan.date='2026.09.07 자료 확인';nolan.faq[0][1]='확인한 자료에서 인터스텔라가 누적 10,387,691명으로 가장 높습니다.';nolan.faq[1][1]='9월 7일 KOBIS에서 조회한 9월 6일까지의 관객 수 10,027,997명입니다.';nolan.faq[2][1]='아닙니다. 상위 5편은 KOBIS 조회값, 나머지 3편은 각 행에 적힌 보도 기준의 반올림값입니다.';nolan.basis='국내 누적 관객 · KOBIS 조회 및 보도 · 작품별 기준일';nolan.source='KOBIS 직접 조회·전작 흥행 보도';nolan.sourceUrl=formerUrl;nolan.description='놀란 감독의 국내 흥행작 8편을 누적 관객으로 비교합니다. 오디세이는 10,027,997명으로 2위를 유지하며 인터스텔라 기록에 접근했습니다. 작품별 집계 시점이 달라 재개봉·보정 이후 합계와 차이가 날 수 있습니다.';
 const spider=get('spider-man-worldwide-box-office');spider.date='2026년 8월 31일 확인';spider.rows[0].value='$2,332,507,928';spider.rows[0].note='2026 · Box Office Mojo 전 세계 누적 매출';spider.rows[0].sourceUrl='https://www.boxofficemojo.com/year/world/2026/';
 Object.assign(get('korean-drama-ratings').rows[0],art('First_Love_(1996_TV_series)'));
 Object.assign(get('korea-car-sales').rows[0],art('Hyundai_Grandeur_2026'));
 Object.assign(get('world-tallest-buildings').rows[2],art('Shanghai_Tower_photo'));
 get('korea-car-sales').sourceUrl='https://auto.danawa.com/auto/?Month=2026-08-00&Nation=domestic&Tab=Model&Work=record';
 return pages;
}
