import { extraPages, extraSlugs } from './additions';
import { applyAudit } from './audit';
import { applyPortraits } from './portraits';
import { expansionPages } from './expansion';
import { asianGamesPages } from './asian-games';
import { gamePages } from './games';
import { applyCompletion } from './completion';
export type RankingRow = { name: string; value: string; note: string; image?: string; rank?: number; sourceUrl?: string; imageSource?: string; /** 지난 갱신 대비 순위 변화(+는 상승) 또는 새로 진입 */ change?: number | 'new' };
export type Division = { name: string; champion: string; contenders: string[] };
export type RankingPage = {
  slug: string; title: string; category: string; date: string; basis: string;
  description: string; source: string; sourceUrl: string; rows: RankingRow[];
  faq: [string,string][]; divisions?: Division[]; posterLayout?: boolean;
  auditDate?: string; auditNote?: string; unranked?: boolean; noindex?: boolean;
  /** 값 막대 비교를 숨깁니다. */ hideBars?: boolean;
  /** 항목 링크를 '자료 출처' 대신 이 문구의 버튼으로 보여줍니다. 예: '사이트로 이동' */ rowLinkLabel?: string;
};

const originalPages: RankingPage[] = [
 ...extraPages,
 {slug:"kbo-attendance-2026",title:"2026 KBO 구단 관중 순위",category:"스포츠",date:"2026년 8월 26일",basis:"구단별 누적 홈 관중·정규시즌 565경기 기준",description:"2026 KBO 리그가 역대 최소인 565경기 만에 누적 1,002만 4,140명을 기록한 시점의 구단별 홈 관중 상위 순위입니다. 공개된 100만 관중 돌파 4개 구단을 비교합니다.",source:"KBO 공식 보도자료",sourceUrl:"https://www.koreabaseball.com/MediaNews/Notice/View.aspx?bdSe=12121",rows:[{name:"LG 트윈스",value:"1,326,067명",note:"누적 홈 관중 1위",image:"https://images.unsplash.com/photo-1508344928928-7165b67de128?auto=format&fit=crop&w=1000&q=85"},{name:"삼성 라이온즈",value:"1,261,477명",note:"평균 23,361명 · 평균 관중 1위"},{name:"두산 베어스",value:"1,161,274명",note:"평균 21,505명"},{name:"롯데 자이언츠",value:"1,060,438명",note:"100만 관중 돌파"}],faq:[["2026 KBO 리그는 언제 1,000만 관중을 넘었나요?","8월 26일 565경기 만에 누적 1,002만 4,140명을 기록했습니다."],["홈 관중이 가장 많은 구단은 어디인가요?","8월 26일 기준 LG 트윈스가 132만 6,067명으로 1위입니다."],["평균 관중 1위도 LG인가요?","아닙니다. 평균 관중은 삼성 라이온즈가 2만 3,361명으로 1위입니다."]]},
 {slug:"mlb-korean-career-earnings",title:"MLB 한국 선수 역대 연봉 순위",category:"스포츠",date:"2026년 8월",basis:"MLB 정규계약 누적 수입 추정",description:"한국인 메이저리거가 MLB에서 받은 누적 연봉을 비교합니다. 계약 총액과 실제 수령액은 옵션·부상·마이너 계약에 따라 차이가 날 수 있습니다.",source:"Spotrac·Baseball Reference",sourceUrl:"https://www.baseball-reference.com/leaders/leaders_salaries.shtml",rows:[{name:"추신수",value:"약 1억 3,900만 달러",note:"외야수"},{name:"류현진",value:"약 1억 2,138만 달러",note:"투수"},{name:"박찬호",value:"약 8,500만 달러",note:"투수"},{name:"김병현",value:"약 3,300만 달러",note:"투수"},{name:"김하성",value:"약 2,800만 달러+",note:"내야수"}],faq:[["한국인 MLB 누적 연봉 1위는 누구인가요?","공개 계약 자료 기준으로 추신수가 가장 높은 수준입니다."],["계약 총액과 실제 연봉은 같나요?","옵션·보너스·지급 유예 때문에 실제 수령액은 달라질 수 있습니다."]]},
 {slug:"korean-football-salary",title:"한국 축구선수 연봉 순위",category:"스포츠",date:"2026년 8월 24일",basis:"세전 고정급 공개 보도·추정",description:"유럽과 MLS에서 활동하는 한국 축구선수의 연봉을 원화로 비교합니다. 이강인의 AT마드리드 이적과 8월 20일 공식 데뷔전 결승골·경기 MVP 이슈를 반영했습니다.",source:"Capology·MLSPA·공개 보도",sourceUrl:"https://www.capology.com/",rows:[{name:"김민재",value:"약 200억~240억원",note:"바이에른 뮌헨"},{name:"손흥민",value:"약 166억원",note:"LAFC"},{name:"이강인",value:"약 100억~110억원",note:"AT마드리드 · 데뷔전 결승골·MVP"},{name:"황희찬",value:"약 80억원",note:"울버햄프턴"},{name:"이재성",value:"약 40억~50억원",note:"마인츠"}],faq:[["이강인의 새 소속팀은 어디인가요?","AT마드리드입니다. 2026년 8월 20일 말라가전에서 공식 데뷔골을 넣고 경기 MVP로 선정됐습니다."],["연봉에 광고 수입도 포함되나요?","아니요. 구단에서 받는 세전 고정급 중심입니다."],["왜 매체마다 연봉이 다른가요?","보너스·환율·세금 포함 방식이 다르기 때문입니다."]]},
 {slug:"ufc-rankings-by-division",title:"UFC 체급별 공식 랭킹",category:"스포츠",date:"2026년 8월 11일",basis:"UFC 공식 미디어 패널 랭킹",description:"UFC 남성부 8개 체급을 챔피언과 상위 랭커로 나누어 정리했습니다. P4P와 체급 랭킹은 서로 다른 순위입니다.",source:"UFC 공식 랭킹",sourceUrl:"https://www.ufc.com/rankings",rows:[{name:"이슬람 마카체프",value:"웰터급 챔피언",note:"P4P 1위"},{name:"알렉산더 볼카노프스키",value:"페더급 챔피언",note:"P4P 상위"},{name:"알렉산드레 판토자",value:"플라이급 1위 랭커",note:"전 챔피언"}],divisions:[{name:"플라이급",champion:"조슈아 반",contenders:["알렉산드레 판토자","마넬 케이프","브랜든 로이발"]},{name:"밴텀급",champion:"페트르 얀",contenders:["메랍 드발리시빌리","션 오말리","우마르 누르마고메도프"]},{name:"페더급",champion:"알렉산더 볼카노프스키",contenders:["모브사르 에블로예프","디에고 로페스","레론 머피"]},{name:"라이트급",champion:"저스틴 게이치",contenders:["일리아 토푸리아","아르만 사루키안","찰스 올리베이라"]},{name:"웰터급",champion:"이슬람 마카체프",contenders:["이안 마차도 개리","카를로스 프라치스","마이클 모랄레스"]},{name:"미들급",champion:"션 스트릭랜드",contenders:["함자트 치마예프","드리커스 뒤 플레시","나수르딘 이마보프"]},{name:"라이트헤비급",champion:"카를로스 울버그",contenders:["마고메드 안칼라예프","유리 프로하스카","알렉스 페레이라"]},{name:"헤비급",champion:"톰 아스피날",contenders:["시릴 간","알렉산더 볼코프","커티스 블레이즈"]}],faq:[["UFC 랭킹은 누가 정하나요?","UFC가 선정한 미디어 패널 투표로 결정됩니다."],["챔피언도 1위에 포함되나요?","챔피언은 별도이며 그 아래부터 랭커 1위가 시작됩니다."],["P4P는 무엇인가요?","체급 차이를 제외하고 선수의 종합 기량을 비교하는 순위입니다."]]},
 {slug:"korean-movie-admissions",title:"역대 국내 영화 관객 순위",category:"미디어",date:"2026년 8월",basis:"국내 개봉작 누적 관객",description:"영화진흥위원회 통합전산망을 기준으로 국내에서 가장 많은 관객을 동원한 영화를 정리합니다.",source:"영화진흥위원회 KOBIS",sourceUrl:"https://www.kofic.or.kr/kofic/business/infm/introBoxOffice.do",rows:[{name:"명량",value:"1,761만명+",note:"2014",image:"/ranking-images/myungryang.jpg"},{name:"극한직업",value:"1,626만명+",note:"2019",image:"/ranking-images/extreme-job.jpg"},{name:"왕과 사는 남자",value:"1,600만명+",note:"2026"},{name:"신과함께-죄와 벌",value:"1,441만명+",note:"2017",image:"/ranking-images/along-gods.jpg"},{name:"국제시장",value:"1,426만명+",note:"2014",image:"/ranking-images/ode-father.jpg"}],faq:[["역대 관객 수 1위 영화는 무엇인가요?","KOBIS 누적 관객 기준으로 명량입니다."],["재개봉 관객도 포함되나요?","KOBIS 누적 집계에는 재개봉 실적이 반영돼 수치가 변할 수 있습니다."]]},
 {slug:"korea-box-office-2026",title:"2026년 국내 영화 흥행 순위",category:"미디어",date:"2026년 8월 27일",basis:"영화관입장권통합전산망 누적 관객",description:"2026년 국내 극장에서 가장 많은 관객을 모은 영화를 누적 관객 수로 비교합니다. 오디세이·스파이더맨 최신 누적 관객과 8월 26일 개봉한 경주기행 이슈를 반영했습니다.",source:"영화진흥위원회 KOBIS·공개 집계",sourceUrl:"https://www.kobis.or.kr/kobis/business/stat/boxs/findYearlyBoxOfficeList.do",rows:[{name:"왕과 사는 남자",value:"약 1,691만명",note:"2026년 1위",image:"/ranking-images/posters/kings-warden.png"},{name:"스파이더맨: 브랜드 뉴 데이",value:"8,263,207명",note:"상영 중",image:"https://feeds.abplive.com/onecms/images/uploaded-images/2025/08/23/429ba9a62aa22bc1ecb3e3afe9e228041755945548628969_original.jpg"},{name:"오디세이",value:"7,656,205명",note:"8월 26일 일별 박스오피스 1위 · 상영 중",image:"https://miro.medium.com/v2/resize:fit:1200/1%3AKeIZg4MKKJSYZfw04mYGbA.jpeg"},{name:"벌집",value:"약 595만명",note:"2026년 상위권",image:"https://kobis.or.kr/common/mast/movie/2026/05/00270422360443cdbac6e2eb5ac856ae.jpg"},{name:"희망",value:"4,526,614명",note:"8월 26일까지 누적",image:"https://img.sbs.co.kr/newsnet/etv/upload/2026/07/03/30001072179.jpg"}],faq:[["2026년 국내 흥행 1위 영화는?","8월 27일 기준 왕과 사는 남자가 약 1,691만명으로 1위입니다."],["스파이더맨과 오디세이 중 누적 관객이 더 많은 작품은?","8월 26일까지 스파이더맨이 826만 3,207명으로 앞서며, 오디세이는 765만 6,205명을 기록했습니다."],["경주기행은 몇 위로 출발했나요?","개봉 첫날인 8월 26일 일별 박스오피스 3위, 한국영화 1위로 출발했습니다."],["관객 수는 계속 바뀌나요?","상영 중인 작품은 KOBIS 일별 집계가 추가되므로 수치와 순위가 달라질 수 있습니다."]]},
 {slug:"worldwide-box-office-2026",title:"2026년 세계 영화 흥행 순위",category:"미디어",date:"2026년 8월 24일",basis:"전 세계 누적 박스오피스·미 달러",description:"스파이더맨: 브랜드 뉴 데이와 오디세이를 포함해 2026년 전 세계에서 가장 많은 극장 매출을 기록한 영화를 비교합니다. 상영 중인 작품은 수시로 변동됩니다.",source:"Box Office Mojo·스튜디오 발표",sourceUrl:"https://www.boxofficemojo.com/year/world/2026/",rows:[{name:"스파이더맨: 브랜드 뉴 데이",value:"약 22.2억 달러",note:"2026년 1위 · 상영 중",image:"https://feeds.abplive.com/onecms/images/uploaded-images/2025/08/23/429ba9a62aa22bc1ecb3e3afe9e228041755945548628969_original.jpg"},{name:"오디세이",value:"약 14.46억 달러",note:"2026년 2위 · 상영 중",image:"https://miro.medium.com/v2/resize:fit:1200/1%3AKeIZg4MKKJSYZfw04mYGbA.jpeg"},{name:"토이 스토리 5",value:"약 11억 달러",note:"2026년 3위권",image:"https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=900&q=85"},{name:"마이클",value:"약 10.2억 달러",note:"마이클 잭슨 전기 영화",image:"https://static.kinoafisha.info/k/movie_posters/800x1200/upload/movie_posters/4/6/3/8369364/789721706374.jpg"},{name:"슈퍼 마리오 갤럭시 무비",value:"약 10.1억 달러",note:"애니메이션",image:"https://images.unsplash.com/photo-1612404730960-5c71577fca11?auto=format&fit=crop&w=900&q=85"}],faq:[["2026년 세계 흥행 1위 영화는?","8월 24일 기준 스파이더맨: 브랜드 뉴 데이가 약 22억 2천만 달러로 1위입니다."],["오디세이 흥행 수익은 얼마인가요?","8월 23일까지 공개 보도 기준 전 세계 약 14억 4,600만 달러입니다."],["순위는 계속 바뀌나요?","상영 중인 작품의 누적 매출이 늘어나므로 주기적으로 갱신해야 합니다."]]},
 {slug:"korean-drama-ratings",title:"역대 한국 드라마 시청률 순위",category:"미디어",date:"역대",basis:"전국 단일회 최고 시청률",description:"지상파 드라마의 전국 최고 시청률 기록을 비교합니다. 시대별 조사 방식과 TV 이용환경이 달라 단순 비교에는 한계가 있습니다.",source:"닐슨코리아 인용 공개자료",sourceUrl:"https://www.nielsenkorea.co.kr/",rows:[{name:"첫사랑",value:"65.8%",note:"KBS2"},{name:"사랑이 뭐길래",value:"64.9%",note:"MBC"},{name:"허준",value:"64.8%",note:"MBC"},{name:"모래시계",value:"64.5%",note:"SBS"},{name:"젊은이의 양지",value:"62.7%",note:"KBS2"}],faq:[["역대 최고 시청률 드라마는?","단일회 최고 시청률 기준 KBS2 첫사랑이 널리 알려진 1위입니다."],["케이블 드라마도 같은 기준인가요?","플랫폼 모집단이 달라 별도 순위로 보는 것이 정확합니다."]]},
 {slug:"ott-content-weekly",title:"OTT 인기 콘텐츠 주간 순위",category:"미디어",date:"2026.08.17~08.23",basis:"대한민국 넷플릭스 TV 주간",description:"한국 넷플릭스에서 한 주 동안 가장 많이 본 TV 프로그램을 공식 주간 차트로 보여줍니다.",source:"Netflix Tudum Top 10",sourceUrl:"https://www.netflix.com/tudum/top10/south-korea/tv",rows:[{name:"나는 SOLO",value:"1위",note:"Part 33"},{name:"우리의 끈끈한 사랑",value:"2위",note:"리미티드 시리즈"},{name:"아파트 잡",value:"3위",note:"리미티드 시리즈"},{name:"귀신들린 연애",value:"4위",note:"리미티드 시리즈"},{name:"틈만 나면,",value:"5위",note:"시즌 1"},{name:"나는 SOLO, 그 후 사랑은 계속된다",value:"6위",note:"2026 Part 2"},{name:"불량연애",value:"7위",note:"시즌 2"},{name:"감사합니다",value:"8위",note:"시즌 1"},{name:"유어 아너",value:"9위",note:"시즌 1"},{name:"나의 AI 파트너 - 이상한 사랑",value:"10위",note:"2026"}],faq:[["이번 주 넷플릭스 한국 TV 1위는?","8월 17일부터 23일까지 나는 SOLO Part 33이 1위입니다."],["순위는 언제 바뀌나요?","넷플릭스가 매주 발표하는 공식 국가별 Top 10에 맞춰 갱신됩니다."],["모든 OTT를 합친 순위인가요?","아니요. 현재 표는 넷플릭스 한국 TV 차트입니다."]]},
 {slug:"korea-car-sales",title:"국내 자동차 월간 판매 순위",category:"라이프",date:"2026년 7월",basis:"국산 승용·RV·소형상용 판매",description:"한 달 동안 국내에서 가장 많이 판매된 국산차 모델을 비교합니다.",source:"KAMA·KAIDA/다나와자동차",sourceUrl:"https://auto.danawa.com/auto/?Work=record",rows:[{name:"더 뉴 그랜저",value:"8,532대",note:"현대"},{name:"셀토스",value:"7,427대",note:"기아"},{name:"카니발",value:"6,917대",note:"기아"},{name:"쏘렌토",value:"6,153대",note:"기아"},{name:"스포티지",value:"5,381대",note:"기아"}],faq:[["판매량과 등록 대수는 같나요?","자료원과 집계 시점에 따라 일부 차이가 날 수 있습니다."],["수입차도 포함되나요?","이 표는 국산 모델 순위이며 수입차는 별도 집계입니다."]]},
 {slug:"korean-travel-destinations",title:"한국인이 많이 찾는 해외여행지",category:"라이프",date:"2025년",basis:"출국·현지 입국 통계 종합",description:"한국인 여행객이 많이 방문한 국가를 각국 입국 통계와 공개 여행 데이터를 종합해 정리합니다.",source:"한국관광 데이터랩·각국 통계",sourceUrl:"https://datalab.visitkorea.or.kr/",rows:[{name:"일본",value:"약 946만명",note:"1위"},{name:"베트남",value:"약 433만명",note:"2위"},{name:"중국",value:"약 316만명",note:"3위권"},{name:"태국",value:"상위권",note:"방콕·푸껫"},{name:"대만",value:"상위권",note:"타이베이"}],faq:[["가장 많이 방문한 국가는?","2025년 공개 통계 기준 일본이 압도적인 1위입니다."],["환승객도 포함되나요?","국가별 통계의 입국자 분류 방식에 따라 차이가 있습니다."]]},
 {slug:"file-sharing-services",title:"파일 공유 서비스 비교 순위",category:"서비스",date:"2026년 8월",basis:"접근성·혜택·콘텐츠 탐색 종합",description:"국내 파일 공유 서비스를 편의성과 혜택을 중심으로 비교합니다. 추천 영역에는 제휴·프로모션이 포함될 수 있습니다.",source:"순위ZIP 편집부 비교",sourceUrl:"/",rows:[{name:"온디스크",value:"추천",note:"신규 혜택·콘텐츠 탐색"},{name:"케이디스크",value:"추천",note:"간편한 이용·모바일 접근"},{name:"파일스타",value:"비교",note:"콘텐츠 구성"},{name:"파일마루",value:"비교",note:"이용 편의"},{name:"예스파일",value:"비교",note:"검색·분류"}],faq:[["순위는 어떤 기준인가요?","접근성·탐색 편의·혜택·모바일 사용성을 종합했습니다."],["광고가 포함됐나요?","제휴 또는 프로모션이 있는 항목은 별도로 표시합니다."]]},
 {slug:"korea-ott-users",title:"국내 OTT 서비스 사용자 순위",category:"서비스",date:"2025년 4월",basis:"스마트폰 앱 월간 사용자",description:"한국인이 많이 사용한 OTT 앱을 월간 활성 사용자 수로 비교합니다.",source:"와이즈앱·리테일",sourceUrl:"https://www.wiseapp.co.kr/",rows:[{name:"넷플릭스",value:"1,341만명",note:"1위"},{name:"쿠팡플레이",value:"738만명",note:"2위"},{name:"티빙",value:"511만명",note:"3위"},{name:"웨이브",value:"230만명",note:"4위"},{name:"디즈니+",value:"193만명",note:"5위"}],faq:[["가입자 수와 MAU는 다른가요?","MAU는 해당 월 앱을 실제 사용한 사람의 추정치입니다."],["PC와 TV 이용도 포함되나요?","해당 조사는 스마트폰 앱 사용자 중심입니다."]]},
 {slug:"japan-av-actress-ranking",title:"일본 AV 배우 인기 순위",category:"글로벌",date:"2026년 8월",basis:"공개 차트·검색 관심·작품 활동 종합",description:"공개 인기 차트와 작품 활동을 종합한 성인 배우 관심도 순위입니다. 만 19세 이상 이용자를 위한 정보입니다.",source:"FANZA 등 공개 차트 종합",sourceUrl:"https://www.dmm.co.jp/",rows:[{name:"카와키타 사이카",value:"상위권",note:"S1"},{name:"이시카와 미오",value:"상위권",note:"MOODYZ"},{name:"코이부치 모모나",value:"상승",note:"신작 관심"},{name:"야기 나나",value:"상위권",note:"작품 활동"},{name:"미카미 유아",value:"레전드",note:"누적 관심"}],faq:[["공식 통합 순위인가요?","아니요. 여러 공개 차트와 관심도를 종합한 편집 순위입니다."],["순위는 얼마나 자주 바뀌나요?","신작과 월간 차트에 따라 수시로 변할 수 있습니다."]]},
 {slug:"highest-paid-athletes",title:"세계 스포츠 스타 수입 순위",category:"글로벌",date:"2025년 발표",basis:"연봉·상금·후원 수입 합산",description:"세계 스포츠 선수의 1년 수입을 경기 수입과 광고·후원 수입을 합산해 비교합니다.",source:"Forbes",sourceUrl:"https://www.forbes.com/lists/athletes/",rows:[{name:"크리스티아누 호날두",value:"2억 7,500만 달러",note:"축구"},{name:"스테픈 커리",value:"1억 5,600만 달러",note:"농구"},{name:"타이슨 퓨리",value:"1억 4,600만 달러",note:"복싱"},{name:"닥 프레스콧",value:"1억 3,700만 달러",note:"미식축구"},{name:"리오넬 메시",value:"1억 3,500만 달러",note:"축구"}],faq:[["수입에는 광고료도 포함되나요?","네. 경기 수입과 후원·사업 수입을 함께 계산합니다."],["세후 수입인가요?","Forbes 추정치는 일반적으로 세전 수입 기준입니다."]]},
 {slug:"world-tallest-buildings",title:"세계 최고층 빌딩 순위",category:"글로벌",date:"2026년 8월",basis:"완공 건축물의 건축적 높이",description:"전 세계 완공 초고층 건축물을 건축적 높이 기준으로 비교합니다.",source:"CTBUH The Skyscraper Center",sourceUrl:"https://www.skyscrapercenter.com/buildings",rows:[{name:"부르즈 할리파",value:"828m",note:"두바이 · 2010",image:"https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1000&q=85"},{name:"메르데카 118",value:"679m",note:"쿠알라룸푸르 · 2023",image:"https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=1000&q=85"},{name:"상하이 타워",value:"632m",note:"상하이 · 2015",image:"https://images.unsplash.com/photo-1548919973-5cef591cdbc9?auto=format&fit=crop&w=1000&q=85"},{name:"메카 로열 클록 타워",value:"601m",note:"메카 · 2012",image:"https://images.unsplash.com/photo-1565552645632-d725f8bfc19a?auto=format&fit=crop&w=1000&q=85"},{name:"핑안 파이낸스 센터",value:"599m",note:"선전 · 2017",image:"https://images.unsplash.com/photo-1522614288668-a697127e9c10?auto=format&fit=crop&w=1000&q=85"},{name:"롯데월드타워",value:"555m",note:"서울 · 2017",image:"https://images.unsplash.com/photo-1538485399081-7c8975d457d9?auto=format&fit=crop&w=1000&q=85"}],faq:[["세계에서 가장 높은 빌딩은?","완공 건축물 기준 두바이의 부르즈 할리파입니다."],["전망대 높이 순위와 같나요?","아닙니다. 이 순위는 건축적 높이를 기준으로 합니다."]]},
 {slug:"world-population",title:"세계 인구 순위",category:"글로벌",date:"UN 2024 전망",basis:"국가·지역별 중위 인구 추계",description:"UN 세계인구전망을 바탕으로 인구가 많은 국가를 비교합니다.",source:"UN World Population Prospects 2024",sourceUrl:"https://population.un.org/wpp/",rows:[{name:"인도",value:"약 14.5억명",note:"1위",image:"https://flagcdn.com/w640/in.png"},{name:"중국",value:"약 14.2억명",note:"2위",image:"https://flagcdn.com/w640/cn.png"},{name:"미국",value:"약 3.45억명",note:"3위",image:"https://flagcdn.com/w640/us.png"},{name:"인도네시아",value:"약 2.83억명",note:"4위",image:"https://flagcdn.com/w640/id.png"},{name:"파키스탄",value:"약 2.51억명",note:"5위",image:"https://flagcdn.com/w640/pk.png"}],faq:[["현재 인구 1위 국가는?","UN 추계 기준 인도입니다."],["인구 수는 실시간 집계인가요?","아닙니다. 출생·사망·이동 자료를 반영한 추계입니다."]]},
 {slug:"korea-province-population",title:"대한민국 시도 인구 순위",category:"라이프",date:"2026년 7월",basis:"주민등록 총인구·외국인 제외",description:"행정안전부 주민등록 인구통계로 시도별 인구를 비교합니다.",source:"행정안전부 주민등록 인구통계",sourceUrl:"https://jumin.mois.go.kr/statMonth.do",rows:[{name:"경기도",value:"약 1,370만명",note:"전국 1위",image:"https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?auto=format&fit=crop&w=1000&q=85"},{name:"서울특별시",value:"928만 4,263명",note:"특별시",image:"https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=1000&q=85"},{name:"부산광역시",value:"323만 982명",note:"광역시",image:"https://images.unsplash.com/photo-1578469645742-46cae010e5d4?auto=format&fit=crop&w=1000&q=85"},{name:"경상남도",value:"약 320만명",note:"도",image:"https://images.unsplash.com/photo-1546874177-9e664107314e?auto=format&fit=crop&w=1000&q=85"},{name:"인천광역시",value:"약 305만명",note:"광역시",image:"https://images.unsplash.com/photo-1624601573012-efb68931cc8f?auto=format&fit=crop&w=1000&q=85"}],faq:[["외국인도 포함되나요?","이 표의 주민등록 인구에는 외국인이 포함되지 않습니다."],["언제 갱신되나요?","행정안전부 통계는 매월 말 기준으로 공표됩니다."]]},
 {slug:"korea-highest-mountains",title:"대한민국 높은 산 순위",category:"라이프",date:"2026년",basis:"대한민국 영토 내 정상 해발고도",description:"대한민국에서 해발고도가 높은 산을 대표 정상 높이로 비교합니다.",source:"국토지리정보원·국립공원공단",sourceUrl:"https://www.ngii.go.kr/",rows:[{name:"한라산",value:"1,947m",note:"제주",image:"https://images.unsplash.com/photo-1604145559206-e3bce0040e2d?auto=format&fit=crop&w=1000&q=85"},{name:"지리산",value:"1,915m",note:"천왕봉",image:"https://images.unsplash.com/photo-1579531403068-8d6fd2b3f45d?auto=format&fit=crop&w=1000&q=85"},{name:"설악산",value:"1,708m",note:"대청봉",image:"https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1000&q=85"},{name:"덕유산",value:"1,614m",note:"향적봉",image:"https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1000&q=85"},{name:"계방산",value:"1,577m",note:"강원",image:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85"}],faq:[["대한민국에서 가장 높은 산은?","제주도의 한라산으로 해발 1,947m입니다."],["북한의 산도 포함하나요?","아니요. 대한민국 행정구역 내 산만 포함합니다."]]},
 {slug:"world-gdp-ranking",title:"세계 GDP 순위",category:"글로벌",date:"IMF 2026년 전망",basis:"명목 국내총생산·현재 미 달러",description:"IMF 세계경제전망의 명목 GDP 전망치를 기준으로 경제 규모가 큰 국가를 비교합니다. 환율과 전망 수정에 따라 값은 바뀔 수 있습니다.",source:"IMF World Economic Outlook",sourceUrl:"https://www.imf.org/external/datamapper/NGDPD@WEO/OEMDC/ADVEC/WEOWORLD",rows:[{name:"미국",value:"약 31.8조 달러",note:"1위",image:"https://flagcdn.com/w640/us.png"},{name:"중국",value:"약 20.7조 달러",note:"2위",image:"https://flagcdn.com/w640/cn.png"},{name:"독일",value:"약 5.3조 달러",note:"3위",image:"https://flagcdn.com/w640/de.png"},{name:"인도",value:"약 4.5조 달러",note:"4위권",image:"https://flagcdn.com/w640/in.png"},{name:"일본",value:"약 4.5조 달러",note:"4위권",image:"https://flagcdn.com/w640/jp.png"}],faq:[["GDP 1위 국가는 어디인가요?","IMF 명목 GDP 전망 기준 미국입니다."],["실질 GDP와 무엇이 다른가요?","명목 GDP는 해당 연도의 시장가격과 환율을 반영하며, 실질 GDP는 물가 변화를 제거합니다."]]},
 {slug:"world-largest-countries",title:"세계에서 가장 큰 나라 순위",category:"글로벌",date:"2023년 최신 공표",basis:"육지 면적·제곱킬로미터",description:"FAO 기반 세계은행 육지 면적 자료로 영토가 넓은 국가를 비교합니다. 내수면 포함 여부에 따라 다른 순위표와 차이가 날 수 있습니다.",source:"World Bank·FAOSTAT",sourceUrl:"https://data.worldbank.org/indicator/AG.LND.TOTL.K2",rows:[{name:"러시아",value:"약 1,638만㎢",note:"1위",image:"https://flagcdn.com/w640/ru.png"},{name:"중국",value:"약 938만㎢",note:"2위권",image:"https://flagcdn.com/w640/cn.png"},{name:"미국",value:"약 915만㎢",note:"2위권",image:"https://flagcdn.com/w640/us.png"},{name:"캐나다",value:"약 879만㎢",note:"4위",image:"https://flagcdn.com/w640/ca.png"},{name:"브라질",value:"약 836만㎢",note:"5위",image:"https://flagcdn.com/w640/br.png"}],faq:[["캐나다가 2위 아닌가요?","총면적 기준으로는 캐나다가 2위지만, 이 페이지는 호수 등 내수면을 제외한 육지 면적 기준입니다."],["자료마다 미국과 중국 순서가 다른 이유는?","내수면·연안수역 포함 범위와 측정 기준이 다르기 때문입니다."]]},
 {slug:"world-highest-mountains",title:"세계에서 가장 높은 산 순위",category:"글로벌",date:"2026년",basis:"해발고도·대표 정상",description:"평균 해수면부터 정상까지의 고도를 기준으로 세계에서 가장 높은 산을 정리합니다.",source:"Encyclopaedia Britannica",sourceUrl:"https://www.britannica.com/place/Mount-Everest",rows:[{name:"에베레스트",value:"8,848.86m",note:"네팔·중국",image:"https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1000&q=85"},{name:"K2",value:"8,611m",note:"파키스탄·중국",image:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85"},{name:"칸첸중가",value:"8,586m",note:"네팔·인도",image:"https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=1000&q=85"},{name:"로체",value:"8,516m",note:"네팔·중국",image:"https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1000&q=85"},{name:"마칼루",value:"8,485m",note:"네팔·중국",image:"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1000&q=85"}],faq:[["세계에서 가장 높은 산은?","네팔과 중국 국경의 에베레스트입니다."],["산 밑에서 정상까지의 높이인가요?","아닙니다. 평균 해수면을 기준으로 한 해발고도입니다."]]},
 {slug:"most-visited-countries",title:"세계 관광객 방문 국가 순위",category:"라이프",date:"2024년",basis:"1박 이상 국제 관광객 입국자",description:"UN Tourism과 각국 공표자료를 바탕으로 해외 관광객이 많이 방문한 국가를 정리합니다. 잠정치와 최종치가 다를 수 있습니다.",source:"UN Tourism World Tourism Barometer",sourceUrl:"https://www.unwto.org/un-tourism-world-tourism-barometer-data",rows:[{name:"프랑스",value:"약 1억명",note:"최상위",image:"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=85"},{name:"스페인",value:"약 9,380만명",note:"최상위",image:"https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1000&q=85"},{name:"미국",value:"약 7,240만명",note:"상위권",image:"https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=1000&q=85"},{name:"튀르키예",value:"약 6,060만명",note:"상위권",image:"https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1000&q=85"},{name:"이탈리아",value:"약 5,800만명",note:"상위권",image:"https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1000&q=85"}],faq:[["가장 많이 방문한 나라는 어디인가요?","UN Tourism 공개자료에서 프랑스가 세계 최대 방문국으로 소개됩니다."],["당일 방문객도 포함되나요?","이 표는 원칙적으로 1박 이상 체류한 국제 관광객을 기준으로 합니다."]]}
];

export const pages = applyPortraits(applyCompletion([...applyAudit([...asianGamesPages, ...expansionPages, ...originalPages]), ...gamePages]));
export const pageBySlug = Object.fromEntries(pages.map(p=>[p.slug,p]));
Object.assign(extraSlugs,Object.fromEntries(expansionPages.map(p=>[p.title,p.slug])));
Object.assign(extraSlugs,Object.fromEntries(asianGamesPages.map(p=>[p.title,p.slug])));
Object.assign(extraSlugs,Object.fromEntries(gamePages.map(p=>[p.title,p.slug])));
Object.assign(extraSlugs,Object.fromEntries(pages.map(p=>[p.title,p.slug])));
export const slugByTitle: Record<string,string> = {...extraSlugs,"2026 KBO 구단 관중":"kbo-attendance-2026","MLB 한국 선수 역대 연봉":"mlb-korean-career-earnings","한국 축구선수 연봉":"korean-football-salary","UFC 체급별 랭킹":"ufc-rankings-by-division","역대 국내 영화 관객":"korean-movie-admissions","2026년 국내 영화 흥행":"korea-box-office-2026","2026년 세계 영화 흥행":"worldwide-box-office-2026","역대 드라마 시청률":"korean-drama-ratings","OTT 인기 콘텐츠":"ott-content-weekly","국내 자동차 판매량":"korea-car-sales","한국인이 찾는 여행지":"korean-travel-destinations","파일 공유 서비스 비교":"file-sharing-services","국내 OTT 서비스":"korea-ott-users","일본 AV 배우 인기":"japan-av-actress-ranking","세계 스포츠 스타 수입":"highest-paid-athletes","세계 최고층 빌딩":"world-tallest-buildings","세계 인구":"world-population","대한민국 시도 인구":"korea-province-population","대한민국 높은 산":"korea-highest-mountains","세계 GDP":"world-gdp-ranking","세계에서 가장 큰 나라":"world-largest-countries","세계에서 가장 높은 산":"world-highest-mountains","세계 관광객 방문 국가":"most-visited-countries"};
